### ISSUE TITLE
Stack-buffer-underflow in ASTImporter unit tests

### ISSUE THREAD

**Issue by martong** [Ericsson/clang#308]
Reproduction:
1) set a failing expectation in one of the tests which use the `Fixture`.
2) Compile `ASTTests` with asan and then run the test.

```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ImportFunctions
[ RUN      ] ImportFunctions.ImportPrototypeThenDefinition
../../git/llvm/tools/clang/unittests/AST/ASTImporterTest.cpp:1570: Failure
Value of: false
  Actual: false
Expected: true
FromAST:
TranslationUnitDecl 0x62100000dfd8 <<invalid sloc>> <invalid sloc>
|-TypedefDecl 0x62100000e578 <<invalid sloc>> <invalid sloc> implicit __int128_t '__int128'
| `-BuiltinType 0x62100000e250 '__int128'
|-TypedefDecl 0x62100000e5f0 <<invalid sloc>> <invalid sloc> implicit __uint128_t 'unsigned __int128'
| `-BuiltinType 0x62100000e270 'unsigned __int128'
|-TypedefDecl 0x62100000e990 <<invalid sloc>> <invalid sloc> implicit __NSConstantString 'struct __NSConstantString_tag'
| `-RecordType 0x62100000e6f0 'struct __NSConstantString_tag'
|   `-CXXRecord 0x62100000e650 '__NSConstantString_tag'
|-TypedefDecl 0x62100000ea38 <<invalid sloc>> <invalid sloc> implicit __builtin_ms_va_list 'char *'
| `-PointerType 0x62100000e9f0 'char *'
|   `-BuiltinType 0x62100000e070 'char'
|-TypedefDecl 0x621000052a08 <<invalid sloc>> <invalid sloc> implicit __builtin_va_list 'struct __va_list_tag [1]'
| `-ConstantArrayType 0x6210000529a0 'struct __va_list_tag [1]' 1
|   `-RecordType 0x62100000eb40 'struct __va_list_tag'
|     `-CXXRecord 0x62100000ea98 '__va_list_tag'
`-FunctionDecl 0x621000052ad0 <=================================================================
==12703==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7fff28c578a0 at pc 0x7f0efe73a8c1 bp 0x7fff28c57050 sp 0x7fff28c57048
READ of size 1 at 0x7fff28c578a0 thread T0
    #0 0x7f0efe73a8c0 in ComputeLineNumbers(clang::DiagnosticsEngine&, clang::SrcMgr::ContentCache*, llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul>&, clang::SourceManager const&, bool&) /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/tools/clang/lib/Basic/SourceManager.cpp:1225:12
    #1 0x7f0efe739732 in clang::SourceManager::getLineNumber(clang::FileID, unsigned int, bool*) const /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/tools/clang/lib/Basic/SourceManager.cpp:1289:5
    #2 0x7f0efe738c07 in clang::SourceManager::getPresumedLoc(clang::SourceLocation, bool) const /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/tools/clang/lib/Basic/SourceManager.cpp:1453:21
    #3 0x7f0f00ad6371 in (anonymous namespace)::ASTDumper::dumpLocation(clang::SourceLocation) /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/tools/clang/lib/AST/ASTDumper.cpp:606:26
    #4 0x7f0f00ad5fd2 in (anonymous namespace)::ASTDumper::dumpSourceRange(clang::SourceRange) /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/tools/clang/lib/AST/ASTDumper.cpp:633:3
    #5 0x7f0f00ade58a in (anonymous namespace)::ASTDumper::dumpDecl(clang::Decl const*)::$_8::operator()() const /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/tools/clang/lib/AST/ASTDumper.cpp:1038:5
    #6 0x7f0f00b106b6 in void (anonymous namespace)::ASTDumper::dumpChild<(anonymous namespace)::ASTDumper::dumpDecl(clang::Decl const*)::$_8>((anonymous namespace)::ASTDumper::dumpDecl(clang::Decl const*)::$_8)::{lambda(bool)#1}::operator()(bool) const /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/tools/clang/lib/AST/ASTDumper.cpp:171:9
    #7 0x7f0f00b36117 in std::function<void (bool)>::operator()(bool) const /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_function.h:706:14
    #8 0x7f0f00addedd in void (anonymous namespace)::ASTDumper::dumpChild<(anonymous namespace)::ASTDumper::dumpDecl(clang::Decl const*)::$_8>((anonymous namespace)::ASTDumper::dumpDecl(clang::Decl const*)::$_8) /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/tools/clang/lib/AST/ASTDumper.cpp:136:11
    #9 0x7f0f00acdcc3 in clang::Decl::dump(llvm::raw_ostream&, bool) const /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/tools/clang/lib/AST/ASTDumper.cpp:2541:5
    #10 0x63957e in clang::ast_matchers::Fixture::~Fixture() /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/tools/clang/unittests/AST/ASTImporterTest.cpp:188:60
    #11 0x639a3d in clang::ast_matchers::ImportFunctions_ImportPrototypeThenDefinition_Test::~ImportFunctions_ImportPrototypeThenDefinition_Test() /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/tools/clang/unittests/AST/ASTImporterTest.cpp:1546:1
    #12 0x7f0f0280576a in testing::TestInfo::Run() /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/utils/unittest/googletest/src/gtest.cc:2661:3
    #13 0x7f0f02806367 in testing::TestCase::Run() /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/utils/unittest/googletest/src/gtest.cc:2774:28
    #14 0x7f0f02812948 in testing::internal::UnitTestImpl::RunAllTests() /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/utils/unittest/googletest/src/gtest.cc:4649:43
    #15 0x7f0f028122bf in testing::UnitTest::Run() /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/utils/unittest/googletest/src/gtest.cc:4257:10
    #16 0x7f0f02b672e6 in main /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/utils/unittest/UnitTestMain/TestMain.cpp:51:10
    #17 0x7f0efb78682f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
    #18 0x489138 in _start (/home/egbomrt/WORK/llvm/build/debug_san/tools/clang/unittests/AST/ASTTests+0x489138)

Address 0x7fff28c578a0 is located in stack of thread T0 at offset 0 in frame
    #0 0x7f0f00ad61ff in (anonymous namespace)::ASTDumper::dumpLocation(clang::SourceLocation) /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/tools/clang/lib/AST/ASTDumper.cpp:597

  This frame has 2 object(s):
    [32, 40) 'Color:601'
    [64, 88) 'PLoc:606'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-underflow /home/egbomrt/WORK/llvm/build/debug_san/../../git/llvm/tools/clang/lib/Basic/SourceManager.cpp:1225:12 in ComputeLineNumbers(clang::DiagnosticsEngine&, clang::SrcMgr::ContentCache*, llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul>&, clang::SourceManager const&, bool&)
Shadow bytes around the buggy address:
  0x100065182ec0: 00 00 00 00 f1 f1 f1 f1 04 f2 f8 f2 01 f2 f8 f3
  0x100065182ed0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100065182ee0: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 04 f2 01 f2
  0x100065182ef0: 00 00 f2 f2 04 f2 f8 f3 00 00 00 00 00 00 00 00
  0x100065182f00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x100065182f10: 00 00 00 00[f1]f1 f1 f1 00 f2 f2 f2 00 00 00 f3
  0x100065182f20: f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x100065182f30: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 f2 f2 f2
  0x100065182f40: f8 f2 f8 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x100065182f50: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 f8 f2 f2 f2
  0x100065182f60: f8 f2 f2 f2 f8 f8 f8 f8 f2 f2 f2 f2 f8 f8 f3 f3
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==12703==ABORTING
```

**Comment by martong** [comment]
Actually this error happens only if there is a failing expectation in the tests because then we want to dump the ASTs in the test Fixtrure dtor. That time looks like the buffer for the source Code is corrupted.
