### ISSUE TITLE
check-lldb fails on ctu-clang6

### ISSUE THREAD

**Issue by martong** [Ericsson/clang#362]
ninja check-lldb fails with some strange python errors:
```
[TestThreadAPI.py FAILED]
Command invoked: /usr/bin/python2.7 /home/egbomrt/WORK/llvm2/git/llvm/tools/lldb/test/dotest.py -q --arch=x86_64 --executable /home/egbomrt/WORK/llvm2/build/debug/bin/lldb -s /home/egbomrt/WORK/llvm2/build/debug/lldb-test-traces -S nm -u CXXFLAGS -u CFLAGS -C /home/egbomrt/WORK/llvm2/build/debug/bin/clang --env ARCHIVER=/usr/bin/ar --env OBJCOPY=/usr/bin/objcopy --results-port 43867 -S nm --inferior -p TestThreadAPI.py /home/egbomrt/WORK/llvm2/git/llvm/tools/lldb/packages/Python/lldbsuite/test --event-add-entries worker_index=1:int
 18 out of 606 test suites processed - TestThreadAPI.py
Traceback (most recent call last):
  File "/home/egbomrt/WORK/llvm2/git/llvm/tools/lldb/test/dotest.py", line 7, in <module>
    lldbsuite.test.run_suite()
  File "/home/egbomrt/WORK/llvm2/git/llvm/tools/lldb/packages/Python/lldbsuite/test/dotest.py", line 1129, in run_suite
    import lldb
  File "/home/egbomrt/WORK/llvm2/build/debug/lib/python2.7/site-packages/lldb/__init__.py", line 53, in <module>
    _lldb = swig_import_helper()
  File "/home/egbomrt/WORK/llvm2/build/debug/lib/python2.7/site-packages/lldb/__init__.py", line 49, in swig_import_helper
    _mod = imp.load_module('_lldb', fp, pathname, description)
ImportError: libLLVMX86CodeGen.so.6: cannot open shared object file: No such file or directory

```

**Comment by gerazo** [comment]
The main problem is that libLLVMX86CodeGen.so is generated by the clang part of the build, it is put under lib folder in the build folder but still, the locally generated python packages do not see it. At least, swig is not configured to search in this alternative folder for SOs.
Until I don't have a more elegant solution, the workaround is to specify the library search path by hand:
´´´
LD_LIBRARY_PATH=$(pwd)/lib ninja check-lldb
´´´

**Comment by martong** [comment]
Thank you Zozo, that is great! Now we can execute them in the CI.
